<a href="https://colab.research.google.com/github/rutu8010478521/demoproject/blob/main/Numpy_code.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

# a) Generate a 4x4 identity matrix
identity_matrix = np.identity(4)
print("4x4 Identity Matrix:")
print(identity_matrix)

4x4 Identity Matrix:
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [2]:
# b) Generate two 3x3 matrices with random integers between 1 and 9
matrix1 = np.random.randint(1, 10, size=(3, 3))
matrix2 = np.random.randint(1, 10, size=(3, 3))

print("\nMatrix 1:")
print(matrix1)

print("\nMatrix 2:")
print(matrix2)

# Matrix Addition
matrix_addition = matrix1 + matrix2
print("\nMatrix Addition (Matrix 1 + Matrix 2):")
print(matrix_addition)

# Matrix Multiplication
matrix_multiplication = np.dot(matrix1, matrix2)
print("\nMatrix Multiplication (Matrix 1 * Matrix 2):")
print(matrix_multiplication)


Matrix 1:
[[4 2 4]
 [4 6 7]
 [7 1 7]]

Matrix 2:
[[5 1 3]
 [2 2 1]
 [4 5 6]]

Matrix Addition (Matrix 1 + Matrix 2):
[[ 9  3  7]
 [ 6  8  8]
 [11  6 13]]

Matrix Multiplication (Matrix 1 * Matrix 2):
[[40 28 38]
 [60 51 60]
 [65 44 64]]


In [ ]:
# Lab Assignment 2

# Input: 5x3 matrix
matrix1 = []
print("Enter elements for a 5x3 matrix:")
for i in range(5):
    row = list(map(int, input(f"Enter row {i+1} (3 elements separated by space): ").split()))
    matrix1.append(row)

# Convert list to numpy array
matrix1 = np.array(matrix1)

# Input: 3x2 matrix
matrix2 = []
print("\nEnter elements for a 3x2 matrix:")
for i in range(3):
    row = list(map(int, input(f"Enter row {i+1} (2 elements separated by space): ").split()))
    matrix2.append(row)

# Convert list to numpy array
matrix2 = np.array(matrix2)

# Matrix Multiplication (5x3 matrix * 3x2 matrix)
product_matrix = np.dot(matrix1, matrix2)
print("\nProduct Matrix (5x3 matrix * 3x2 matrix):")
print(product_matrix)

Enter elements for a 5x3 matrix:
